import Svg, { Circle, G, Path, Rect, Text as SVGText, TSpan } from "react-native-svg";
import { View, Text, Dimensions } from "react-native";
import { hierarchy, tree } from "d3-hierarchy";
import { linkVertical } from "d3-shape";

type Data = {
  name: string;
  children?: Data[];
};

const data: Data = {
  name: "Eve",
  children: [
    { name: "Cain" },
    { name: "Seth", children: [{ name: "Enos" }, { name: "Noam" }] },
    { name: "Abel" },
    { name: "Awan", children: [{ name: "Enoch" }] },
    { name: "Azura" },
  ],
};

const NODE_SIZE = {
  width: 100,
  height: 50,
};

const D3Flow = () => {
  const { width: nodeWidth, height: nodeHeight } = NODE_SIZE;
  const root = hierarchy<Data>(data);
  const treeLayout = tree<Data>()
    .nodeSize([nodeWidth + 20, nodeHeight + 40])
    .separation((a, b) => (a.parent === b.parent ? 1 : 2));

  treeLayout(root);

  // Find bounds of the tree
  const nodes = root.descendants();
  const xs = nodes.map(n => n.x || 0);
  const ys = nodes.map(n => n.y || 0);
  const minX = Math.min(...xs);
  const maxX = Math.max(...xs);
  const minY = Math.min(...ys);
  const maxY = Math.max(...ys);

  // Calculate the total dimensions of the tree with padding
  // (maxX - minX) gives the span of x coordinates
  // + nodeWidth * 2 adds padding: nodeWidth on left and nodeWidth on right
  const treeWidth = maxX - minX + nodeWidth * 2;
  const treeHeight = maxY - minY + nodeHeight * 2;

  // Calculate offsets to shift tree into positive coordinate space with padding
  // -minX: negates the minimum x to shift everything right (e.g., if minX is -100, -(-100) = +100)
  // + nodeWidth: adds left padding so nodes don't sit at the edge (x=0) but start at x=nodeWidth
  // Result: leftmost node (originally at minX) now appears at position nodeWidth
  const offsetX = -minX + nodeWidth;

  // Same logic for Y axis:
  // -minY: shifts everything down to remove negative coordinates
  // + nodeHeight: adds top padding so the topmost node appears at y=nodeHeight instead of y=0
  const offsetY = -minY + nodeHeight;

  // Create link generator for curved paths between nodes
  // linkVertical() creates a generator function that produces SVG path data for vertical curves
  // It generates a cubic Bezier curve where control points are positioned vertically
  // between the source and target, creating a smooth S-shaped curve
  type LinkPoint = { x: number; y: number };
  type LinkData = { source: LinkPoint; target: LinkPoint };
  const linkGenerator = linkVertical<LinkData, LinkPoint>()
    // .x() defines how to extract x coordinate from data points
    // This tells the generator where horizontally to place the start/end of the curve
    .x((d) => d.x)
    // .y() defines how to extract y coordinate from data points
    // This tells the generator where vertically to place the start/end of the curve
    .y((d) => d.y);

  // Get all links (connections between parent and child nodes)
  // root.links() returns an array of {source, target} objects where:
  // - source: the parent node
  // - target: the child node
  const links = root.links();

  return (
    <View>
      <Text>D3 Flow</Text>
      <Svg width="100%" height="100%" viewBox={`0 0 ${treeWidth} ${treeHeight}`}>
        {/* Render links first so they appear behind nodes (SVG renders in order) */}
        {links.map((link, i) => {
          // Apply the same offsets to link coordinates as we did to node coordinates
          // This ensures the links connect to the correct node positions after translation
          // link.source is the parent node, link.target is the child node
          const pathData = linkGenerator({
            source: {
              // Parent node x position + horizontal offset for centering
              x: (link.source.x || 0) + offsetX,
              // Parent node y position + vertical offset for centering
              y: (link.source.y || 0) + offsetY,
            },
            target: {
              // Child node x position + horizontal offset for centering
              x: (link.target.x || 0) + offsetX,
              // Child node y position + vertical offset for centering
              y: (link.target.y || 0) + offsetY,
            },
          });
          return (
            <Path
              key={`link-${i}`}
              // d: SVG path data string generated by linkGenerator (e.g., "M100,50 C100,75 150,75 150,100")
              d={pathData || ""}
              // stroke: line color (gray for subtle appearance)
              stroke="#999"
              // strokeWidth: line thickness in pixels
              strokeWidth={2}
              // fill: "none" ensures only the stroke is visible (no filled shape)
              fill="none"
            />
          );
        })}

        {/* Render nodes on top of links */}
        {nodes.map((n) => (
          <NodeG
            key={n.data.name}
            x={(n.x || 0) + offsetX}
            y={(n.y || 0) + offsetY}
            text={n.data.name}
          />
        ))}
      </Svg>
    </View>
  );
};

interface NodeGProps {
  x: number;
  y: number;
  text: string;
  nodeWidth?: number;
  nodeHeight?: number;
}

const NodeG = ({
  x,
  y,
  text,
  nodeWidth = NODE_SIZE.width,
  nodeHeight = NODE_SIZE.height,
}: NodeGProps) => {
  return (
    <G transform={`translate(${x}, ${y})`}>
      <Rect
        x={-nodeWidth / 2}
        y={-nodeHeight / 2}
        width={nodeWidth}
        height={nodeHeight}
        fill="grey"
      />
      <SVGText
        x={0}
        y={0}
        textAnchor="middle"
        alignmentBaseline="middle"
        fontSize={16}
      >
        {text}
      </SVGText>
    </G>
  );
};

export default D3Flow;
